---
- name: Show return value of command module
  hosts: vagrant1
  gather_facts: False
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: var=login
    - debug: msg="Logged in as user {{ login.stdout }}"


    - name: Ignore error
      command: /opt/myprog
      register: result
      ignore_errors: True
    - debug: var=result

# Information discovered from systems: Facts
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#information-discovered-from-systems-facts
- name: Print out OS
  hosts: vagrant1
  gather_facts: True
  tasks:
    - debug: var=ansible_distribution
